version: '3.7'

services:
  csharp-invoicer:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5000
    volumes:
      - ./config/appsettings.json:/app/appsettings.json:r
    ports:
      - "0.0.0.0:50000:5000"

